export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const ADD_TO_CART= 'ADD_TO_CART';
export const CHANGE_MESSAGE= 'CHANGE_MESSAGE';
export const UPDATE_PRODUCT_INCART='UPDATE_PRODUCT_INCART';
export const DELETE_PRODUCT_INCART= 'DELETE_PRODUCT_INCART';
export const ORDER= 'ORDER';
export const CLEAR_CART= 'CLEAR_CART';